package rules

import com.ADNArusBack.dominio.registro.modelo.entidad.Registro
import com.ADNArusBack.dominio.registro.AfiliacionDroolsExcepcion
import java.text.SimpleDateFormat;


rule "Criterio 1"
	when
		usuario: Registro(administradoraPension == "AFP003" && fechaAfiliacionPension < new SimpleDateFormat("dd/MM/yyyy").parse("01/01/2021"))
	then
		throw new AfiliacionDroolsExcepcion("Para la administradora de pension AFP003 solo es posible afiliarse despues de 2020/12/31");
	end

rule "Criterio 2"
	when
		usuario: Registro(tipoDocumento == "RC" && (administradoraSalud == "EPS003" || administradoraSalud == "EPS004" ))
	then
		throw new AfiliacionDroolsExcepcion("Para una persona con tipo de documento RC Registro civil no es permitido afiliarse a las EPS: EPS003, EPS004");
	end

rule "Criterio 3"
	when
		usuario: Registro(administradoraSalud == "EPS002" && administradoraPension != "AFP001" )
	then
		throw new AfiliacionDroolsExcepcion("Las personas que se afilien a la administradora EPS002 Sura EPS solo pueden afiliarse a la administradora de pension AFP001 Proteccion");
	end